### ISSUE TITLE
Changes need to be made to the interface in the xfescangrid

### ISSUE THREAD

**Issue by sergiogf93** [ispyb/EXI#119]

**Comment by antolinos** [comment]
Could you please give a extended description of the issue?

Thanks,
A.

**Comment by sergiogf93** [comment]
The **Energy** values are used on the x-axis by default.

Also, the **continuum** and **pileup** values are not displayed by default.

![image](https://cloud.githubusercontent.com/assets/22632506/23256049/2ba3a900-f9be-11e6-9e44-a534a63b3b33.png)
