### ISSUE TITLE
Cell parameters in characterisation results

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/EXI#122]
The cell parameters in the auto-processing results are displayed differently compared with the characterisation result :
![image](https://cloud.githubusercontent.com/assets/1306808/23068132/a3a95936-f522-11e6-885f-817e4512d252.png)
![image](https://cloud.githubusercontent.com/assets/1306808/23068152/c2ae339c-f522-11e6-8469-cdcb4051ba23.png)

**Comment by olofsvensson** [comment]
I have a patch ready which make the characterisation results look like this:
![image](https://cloud.githubusercontent.com/assets/1306808/23068243/28a8fc7c-f523-11e6-97cf-38c3b211e2de.png)

**Comment by StephMonaco** [comment]
:-)
thanks!
stephanie
