### ISSUE TITLE
Strange "InnerShell	OuterShell	Overall" headings on results tab

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/EXI#128]
I just discovered this:
![image](https://cloud.githubusercontent.com/assets/1306808/23071146/af6fcac4-f52d-11e6-9227-068e3583f87d.png)
To me it seems like the "InnerShell	OuterShell	Overall" headings are from an old version of this table and should be deleted.

**Comment by antolinos** [comment]
These headings are the legend that is used to interpret the colors of the columns: inner, outer and overall (and it may be necessary to put it back)

**Comment by olofsvensson** [comment]
Ok, what about something like this:
![image](https://cloud.githubusercontent.com/assets/1306808/23607032/97d16916-0263-11e7-9ad3-4940e96f1353.png)

**Comment by StephMonaco** [comment]
Yes that  looks good.
would that be possible to get the following order : overall then inner then Outer?
Thanks

**Comment by olofsvensson** [comment]
Yes, it's indeed a good idea to start with the overall shell:

![image](https://cloud.githubusercontent.com/assets/1306808/23648038/31c189a6-0319-11e7-98e3-89198b37ee18.png)

Stéphanie, if you are happy with this design I'll submit a pull request.

**Comment by olofsvensson** [comment]
Deployed in production.
