### ISSUE TITLE
Change time to 24H format

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/EXI#132]
I find it quite confusing to have the time in the summary tab in AM / PM format:

![image](https://cloud.githubusercontent.com/assets/1306808/23123024/0031f00a-f767-11e6-848b-d0a9a5af3a63.png)

What's even more confusing is that in the "Data collection summary" view the format is the same without AM / PM:

![image](https://cloud.githubusercontent.com/assets/1306808/23123068/28316748-f767-11e6-9c96-f616ec2272da.png)

I therefore suggest that we change the time format to 24H.

**Comment by antolinos** [comment]
As this date formatting may be needed in several places I would recommend to use the already implemented dust helper function in helpers.js


```
dust.helpers.formatDate = function (chunk, context, bodies, params) {
    if (params.date) {
        if (params.date){
            if (params.format != null) {
                try {
                    formatted = moment(new Date(params.date)).format(params.format);
                    chunk.write(formatted);
                } catch (e) {
                    chunk.write(params.date);
                }
            } else {
                chunk.write(params.date);
            }
        }
    }
    return chunk;
}

```
