### ISSUE TITLE
Download all autoProcResults for a dataCollection

### ISSUE THREAD

**Issue by sergiogf93** [ispyb/EXI#144]
Add a button at the data collections summary for downloading the autoProc results:

![image](https://cloud.githubusercontent.com/assets/22632506/23306382/b66b0340-faa3-11e6-8ff7-e0b917732a54.png)

**Comment by antolinos** [comment]
Webservices now handles to download multiple results so it is not needed anymore to use jsZIP and file-saver in the client side what will make things simpler

Then I would recommend to:
- Use the link to download all the results in the same zip. For instance:
http://ispyvalid:8080/ispyb/ispyb-ws/rest/{token}/proposal/{proposal}/mx/autoprocintegration/attachment/autoprocprogramid/970307,970311/download
- Remove code for downloading the files step by step
- Remove unused dependencies

https://github.com/ispyb/ISPyB/issues/48
https://github.com/ispyb/ISPyB/pull/49
