### ISSUE TITLE
Problem with range in characterisation results

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/EXI#154]
There's a problem with how the oscillation range is reported for characterisations in the summary view:

![image](https://cloud.githubusercontent.com/assets/1306808/23696448/f8563cb8-03e3-11e7-9e46-74f0a53b85f4.png)

The value of "total rotation" acutally corresponds to the "oscillation range" for one image.

**Comment by olofsvensson** [comment]
Suggested new design:

![image](https://cloud.githubusercontent.com/assets/1306808/23696959/23ee24ce-03e6-11e7-92ec-1b415d3d081f.png)

I'll open a PR with this patch.

**Comment by StephMonaco** [comment]
we could have Osc. range (total) 0.15 (30)
and Osc. start 67
what do you think?

**Comment by olofsvensson** [comment]
Good idea! Some changes might be necessary on the ISPyB web service side as I don't have access to the oscillation start. I'll check with Alejandro.

**Comment by antolinos** [comment]
Could this issue be closed?

**Comment by StephMonaco** [comment]
yes ;-)
