### ISSUE TITLE
Manager search

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#165]
we need a tool as manager to search for sessions for : 
- proposal (part of a proposal name) as in the search for proposal today)
- AND/OR for a period (from Date to Date)
- AND/OR with tick boxes for all BLs - if not ticked all BLs are searched for otherwise a few tick boxes will search for that particular set of Bls

**Comment by sergiogf93** [comment]
![image](https://cloud.githubusercontent.com/assets/22632506/24143524/415faf34-0e2a-11e7-9f98-4fed3000fa0f.png)
