### ISSUE TITLE
Modifications in edit Crystal Form

### ISSUE THREAD

**Issue by delageniere** [ispyb/EXI#191]
The field "name" should be removed from creation and edition.
In edition mode only cell parameters should be editable, space group is locked.

Note that all samples attached to a crystal form edited are still attached to the edited crystal form (and the cell parameters may not be any more what they were at the time the samples were created).

**Comment by StephMonaco** [comment]
"Note that all samples attached to a crystal form edited are still attached to the edited crystal form (and the cell parameters may not be any more what they were at the time the samples were created)."
Maybe on the Edit menu one should mention that modifying this crystal form will modify it for all samples of the database described with this crystal form, and a new crystal card might be more appropriate? I don't know how to phrase it in a few words ;)
