### ISSUE TITLE
Reso for outer shell in autoproc stats results : 2digits

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#200]
increase resolution digits to 2 for outer shell :
![capture](https://cloud.githubusercontent.com/assets/25433590/24866377/32df34e4-1e0a-11e7-9948-ef3051d3443c.PNG)

in the session summary and in the summary table with all autoproc results.
no need to increase this in the other shells (inner and overall)

[feedback from Daniele]

**Comment by antolinos** [comment]
It is deployed now. To be tested. Please, flag as TESTED if it works please and then close it.
