### ISSUE TITLE
Barcode generation is * NULL* from EXI?

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#201]
It seems to me that when a shipment is created from EXI the barcode generated is NULL which is wrong!
I have seen that with MX415.
Could you check that there is no missing step in the process?
Thanks

**Comment by delageniere** [comment]
In ispyb-ui, when creating a dewar, the dewarId is then used to generate the bar code. It is not the case in EXI.
We should move this barcode automatic generation in ispyb-ejb at the level of dewar creation, so it would then be used from ispyb-ui as well as from EXI.

**Comment by antolinos** [comment]
Hi @delageniere ,

Can we close this ticket?
