### ISSUE TITLE
Prepare experiment window - parcel not filled properly

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#202]
When doing a prepare experiment in EXI, access to the shipments list, select a shipment and go to 2nd interface with list of containers in the selected shipments. The column parcel is filled today with the container names and note the parcel names. 
![capture](https://cloud.githubusercontent.com/assets/25433590/24948077/6efbf7e0-1f69-11e7-961c-3cf4a6ba3cc7.PNG)

**Comment by antolinos** [comment]
I will deploy this fix today. If happy with it please close it.
