### ISSUE TITLE
Notification of success/failure for autoprocessings

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#204]
linked with https://github.com/ispyb/ispyb-database-modeling/issues/3
in EXI when a data collection doesn't lead to autoprocessing results because there is no crystallographic data in the images for example, we have **2** results in the Latest Collect results subTAB (entries from EDNA) despite the fact that there is no result:
![capture](https://cloud.githubusercontent.com/assets/25433590/24959968/9c24f520-1f94-11e7-93e3-125960d74806.PNG)
![capture1](https://cloud.githubusercontent.com/assets/25433590/24959975/a012c1c6-1f94-11e7-9d1f-705ceb0d7c29.PNG)
ideally we want to view that processes were launched and led to no result and the why it failed (log files from the pipelines); In a first phase we should have no number in the autproc results subTAB.
Maybe later:  # of autoproc ran, # of results

**Comment by antolinos** [comment]
![image](https://cloud.githubusercontent.com/assets/2901169/24960964/a02fea78-1f97-11e7-93ec-670a1bb18b33.png)

Hi,

What about to display the number of results (because they exist) and isplay them as failed?

**Comment by StephMonaco** [comment]
I like this idea but I thought this would be too demanding.. then thiw ould allow us to access to the logfile to understand why it has failed. When they are copied on pyarch

In that case failed would have the same colour as bad autoproc result, no? to be checked - I would prefer they don't ;)

**Comment by antolinos** [comment]
Summray displays an overview of the pipelines executed similar to:
![image](https://cloud.githubusercontent.com/assets/2901169/24961902/8e818072-1f9a-11e7-83f4-8b9a8996331d.png)

Then someone can click on them and go to the list of files attached where you can dig into the logs (if any)

Question is: Last Collect Results(X), do we want X to be the number of pipelines executed or number of pipelines executed with results?

**Comment by StephMonaco** [comment]
YES!!
pipelines executed with results is best 
Thanks!

**Comment by antolinos** [comment]
Then where are the pipelines with no results displayed?
