### ISSUE TITLE
SC view in the prepare experiment doesn't display the pucks

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#212]
we don't see the pucks in the SC view (just the one that is highlighted), neither the samples within these pucks. Might be related with issue #210 
![capture](https://cloud.githubusercontent.com/assets/25433590/25891976/325ddb6c-3573-11e7-9b8c-bab6a48471d5.PNG)

**Comment by antolinos** [comment]
I made a fix but still we need to understand this
https://github.com/ispyb/ISPyB/issues/101

![image](https://cloud.githubusercontent.com/assets/2901169/25943139/2f859cfa-363f-11e7-8f15-0f1fc9ad556d.png)
