### ISSUE TITLE
Display of autoproc results XSCALE

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#213]
* Could the graphs be on the same X scale as it was in ISPYB ? snapshots from ISPYB and EXI displaying the same results: 
![capture](https://cloud.githubusercontent.com/assets/25433590/25901927/7405a9f8-3598-11e7-8bdf-2cad0f831940.PNG)
![capture1](https://cloud.githubusercontent.com/assets/25433590/25901926/7404e572-3598-11e7-980a-49ad7dc63bd3.PNG)
* make sure that when we click on an autoproc result from the summary page the attached files are displayed on the right panel (this is confusing otherwise)
* keep cc1/2 as it is now : from 0 to 100 ;)
Thanks

**Comment by antolinos** [comment]
Y axis of cc2 vs resolution should be from 0 to 100

![image](https://cloud.githubusercontent.com/assets/2901169/25987385/108611da-36f4-11e7-9bab-1d3dab19e89a.png)

**Comment by antolinos** [comment]
Overall view:
![image](https://cloud.githubusercontent.com/assets/2901169/25987496/8f7ac47c-36f4-11e7-82fb-5095caea92b4.png)
