### ISSUE TITLE
Direct link to the AForm in the sessions list for local contacts is missing in EXI

### ISSUE THREAD

**Issue by delageniere** [ispyb/EXI#215]
Reported by David Flot: the link to go directly to the AForm of the experiment is missing in EXI page.
A button should be provided for local contacts in the sessions list so that they have direct access to the AForm.

**Comment by StephMonaco** [comment]
I would extend it to all - Users might find it useful too and this would avoid to complicate the various views depending on the user type (LC, manager...)

**Comment by antolinos** [comment]
To be tested in prod

![image](https://user-images.githubusercontent.com/2901169/26885633-70c84f18-4ba3-11e7-95f0-03815d777b26.png)

**Comment by StephMonaco** [comment]
That's working and great!
You can close it
Thanks

**Comment by antolinos** [comment]
Hi @StephMonaco,

Feel free to tag as DEPLOYED and TESTED and then close it. Otherwise I got them lost in my in-mail.

Thanks,
A.

**Comment by delageniere** [comment]
The link to the AForm should be hidden if session is cancelled.
When a session is cancelled the flag "scheduled" is put to 9
See https://github.com/ispyb/ISPyB/issues/136
