### ISSUE TITLE
Edit session comment not implemented yet

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#218]
The comment attached to each session is accessible in the list of sessions displayed in the home page.
The pen sign allows to open a box where the comment can be modified and the save/ close buttons are created but the save button doesn't seem to be implemented meaning really saving the comment in the db:

![capture1a](https://cloud.githubusercontent.com/assets/25433590/26240990/5b807a56-3c83-11e7-8d28-85e449aa672e.PNG)
![capture1b](https://cloud.githubusercontent.com/assets/25433590/26241039/9345ef20-3c83-11e7-87ce-17dfaad3f59f.PNG)
![capture](https://cloud.githubusercontent.com/assets/25433590/26240928/1e22e61c-3c83-11e7-964d-9ab14b58ba20.PNG)

**Comment by antolinos** [comment]
This is deployed now.
