### ISSUE TITLE
creation of a new sample

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#222]
There is no check that there is a unique combination prot acronym-sample within the same shipment.
Please modify this quickly, this is dangerous

**Comment by antolinos** [comment]
After some discussion we agreed that the uniqueness should be done at level of proposal and then a feature to copy/move pucks from one shipment to other will be necessary.

**Comment by antolinos** [comment]
- Upon save: check that acro-sample name is unique for this proposal and within the shipment. If that's not the case, warn the user with a description of the samples in conflict
