### ISSUE TITLE
Increase text size for phasing plots column heads

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/EXI#232]
Stephanie pointed out the the column heads for the phasing plots are not very readable:

![image](https://cloud.githubusercontent.com/assets/1306808/26633623/4eff323c-4614-11e7-98d1-c6b0da7759bf.png)

**Comment by olofsvensson** [comment]
Stéphanie also suggested new tool tips:

- DSIGMA RESOLUTION : "anomalous signal vs resolution - from SHELXC"
- CCALL CCWEAK : "CCall vs CCweak - from SHELXD"
- OCCUPANCY SITENUMBER : " Site occupancy vs peak number - from SHELXE" 
- CONTRAST CYCLE : "contrast between solvent and non-solvent regions per cycle - from SHELXE"

**Comment by StephMonaco** [comment]
tool tips and font size are fine.
Thanks!

**Comment by olofsvensson** [comment]
I checked with Stéphanie and it looks good now.
