### ISSUE TITLE
BioSAXS: add Sample volume to Analysis view

### ISSUE THREAD

**Issue by maaeli** [ispyb/EXI#246]
For some sample changer studies, the sample volume is an important measurement identifier that should be displayable in the Analysis view

**Comment by antolinos** [comment]
Hi @maaeli,

Is that volume to load?

**Comment by maaeli** [comment]
Hi,

I guess so. It is referred to as Vol. Load in the Measurement view of the ISPyB GUI...

Thanks!

**Comment by antolinos** [comment]
![image](https://user-images.githubusercontent.com/2901169/27873403-4adce236-61ac-11e7-8657-3275a5428dfe.png)

**Comment by maaeli** [comment]
Thank you!
