### ISSUE TITLE
Default number of shifts should be 1

### ISSUE THREAD

**Issue by maaeli** [ispyb/EXI#249]
For non-scheduled experiments exi (ispyb?) always lists 3 shifts. I think 1 shift  would be more realistic. No information at all might be even better

**Comment by antolinos** [comment]
Hi @maaeli 

It is defined on ISPyB and not EXI. It is like a default value, is that really something we should need to change?

**Comment by StephMonaco** [comment]
The problem is that if a non scheduled experiment lasts longer than 1 shift and if there is an mxcube restart a new session will appear in ISPYB. I don't think we should change this at the moment. To me this should be thought carrefully and for all experiment types BIOSAXS, MX.
