### ISSUE TITLE
Make it possible to create links to session results

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/EXI#253]
In the MXPressA workflow (e.g. running on MASSIF 1) an email is automatically sent to the shipment contact person every time a new protein has started to be collected. It would be great if we could include a link in the URL that would take the user directly to the corresponding session web page in EXI.

Of course the token would not exist in the link, so the user would need to login into EXI. What is needed is to enable the user to be automatically directed to the corresponding EXI web page after having logged in.

**Comment by antolinos** [comment]
Hi @olofsvensson,

I would need to get from URL the proposal too. For instance:
http://lindemaria:8082/EXI/mx/dev.html#/mx/datacollection/session/58814/main?proposal=mxXXXX

Would it be possible?

**Comment by antolinos** [comment]
I changed my mind. Links are like:
a) For a single data collection
http://exi.esrf.fr/mx/#/mx/proposal/mx1831/datacollection/datacollectionid/2071754/main

b) For a session
http://exi.esrf.fr/mx/#/mx/proposal/mx1831/datacollection/session/58449/main
