### ISSUE TITLE
Autoproc result display XIA2_DIALS (DC summary & session summary)

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#261]
- it would be good to highlight (results in red for Rmerg values? or background of autoproc result in light red?) bad autoproc result in the session summary and in the View all collects if only this one is available out of all pipelines. Same function that displays the autoproc result in red in the autoproc results display (low reso Rmerg >10)
- in the case below XIA2_DIALS results are displayed properly in the session summary but with too many decimals in the view all collections view
![capture](https://user-images.githubusercontent.com/25433590/27434537-534cb138-5759-11e7-83c1-c74970ad3c59.PNG)
![capture1](https://user-images.githubusercontent.com/25433590/27434545-588d3c4e-5759-11e7-9ad6-afe92c12b7c1.PNG)

**Comment by antolinos** [comment]
I propose the following to highlight bad results

![untitled drawing](https://user-images.githubusercontent.com/2901169/27486531-314247a0-5831-11e7-8bbe-5c9c05b09f22.jpg)

**Comment by antolinos** [comment]
Colors are back
![image](https://user-images.githubusercontent.com/2901169/27639336-29c4602e-5c16-11e7-93f7-23ed4c8a5856.png)
