### ISSUE TITLE
BioSAXS/Sample Changer: filenames

### ISSUE THREAD

**Issue by maaeli** [ispyb/EXI#292]
Could we show the actual filename somewhere? And possibly, e.g. in the plate setup view, the place it was saved? That would make it much easier to actually locate the data if one already has it...

**Comment by antolinos** [comment]
Filename of..?

Do you mean to add a new column in here?
![image](https://user-images.githubusercontent.com/2901169/28527356-8854d6a4-708a-11e7-92a2-a1bd62c47c94.png)

**Comment by maaeli** [comment]
Filenames of the _ave.dat files, I guess? The old interface has them. I am not sure where the best place is - Data Analysis would probably the mos useful. The folder should be the same for all measurements in a batch, this is why the plate view came to my mind. But perhaps the measurements tab would be more appropriate...

**Comment by antolinos** [comment]
Could you make a screenshot of the UI and draw a red cross exactly where you would like to see the file name of the average file?
That will speed up this a lot...

**Comment by maaeli** [comment]
![image](https://user-images.githubusercontent.com/4751755/28527882-440f8ed8-708c-11e7-9227-a3c00d9fb258.png)

**Comment by antolinos** [comment]
Filename or filepath?

![image](https://user-images.githubusercontent.com/2901169/28528585-710e1f56-708e-11e7-82ff-7f3c6a28206d.png)

**Comment by antolinos** [comment]
Hi @maaeli,

I just realized that we don't store the file path of /data/visitor but /data/pyarch then file path will not be reachable.
So, this will not work for you at least we add the output folder relative to /data/visitor on ISPyB.

**Comment by maaeli** [comment]
Well, adding the relative folder should not be too complicated, should it? EDNA definitely has that information, passing it on to ISPyB should not be a big deal.
