### ISSUE TITLE
Creation of crystals form of the type SPG-unknown for a protein

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#297]
We miss this tool in EXI (that exists in ISPYB).
Today if a creation of a crystal form for a sample doesn't provide a unit cell the save option is not possible.
We want this option available. 
selection of a protein / Crystal pull down NEW / selection of a SPG / save - fields for the cell parameters should be empty and not filled with 0 values.
and on the next occurence of the protein selection display this last entry by default for crystal form
![capture](https://user-images.githubusercontent.com/25433590/29672636-20f54b30-88ed-11e7-89e2-07c593dd8d99.PNG)

**Comment by antolinos** [comment]
Hi @StephMonaco,

Knowing that we can force now the space group, do we still want to create a crystal form with no unit cell? It is the same as force space group and keeps database nicer and cleaner

**Comment by StephMonaco** [comment]
no that's fine - we can close that
