### ISSUE TITLE
Crystal form pull down menu in shipment

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#298]
Is it possible to display this pull down list by default with :
NEW on top
Then list by alphabetical order
but then keep the latest entry selected as the default until a next one is selected?

**Comment by antolinos** [comment]
![image](https://user-images.githubusercontent.com/2901169/30583305-fa597714-9d26-11e7-97fd-4fb3d9a0c152.png)

**Comment by StephMonaco** [comment]
Thanks!
