### ISSUE TITLE
Update db 

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#300]
create a button for db update (to retrieve the sessions and sample sheets from SMIS) in the upper green panel

**Comment by antolinos** [comment]
Hi @StephMonaco,

What is the label of the button? Only for users (a single proposal) or also for managers (all proposals)?

**Comment by StephMonaco** [comment]
- "Synch SMIS"  should be OK (since we have Synch ISPYB in MXCUBE already 
![image](https://user-images.githubusercontent.com/25433590/30026139-e5702ce6-917b-11e7-94c0-34199be1d67a.png)
 ) - maybe we can add the icon (for Synch ispyb) of MXCUBE3 if that's not too heavy on the interface when Marcus can provide it.

- otherwise for a single proposal is sufficient - if as manager if we go to a proposal we can synch SMIS for that proposal.
Thanks

**Comment by StephMonaco** [comment]
I just received the snapshot of MXcube 3 for the synch ISPYB button
![image](https://user-images.githubusercontent.com/25433590/30203515-848975ea-9482-11e7-9020-e6b844f1f75d.png)
Might be useful to get the exact same design with SMIS.
Not urgent - but I store it here in case you want to go back to it
