### ISSUE TITLE
change "Autoproc" to "Autoprocessing" for the generic autoprocessing pipelines

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#310]
could you change on the EXI interfaces:
![lghhnpfjlhoajapa](https://user-images.githubusercontent.com/25433590/30799446-28fabaaa-a1dd-11e7-9134-ff0433b3ef49.png)

to
![alophfapkhegedma](https://user-images.githubusercontent.com/25433590/30799454-2ff8e87c-a1dd-11e7-816a-26875a5556c7.png)

to avoid mis-interpretations with AUTOPROC from Global Phasing Please?
It seems to only be in the Data collection summary page
Thanks

**Comment by antolinos** [comment]
Can it be closed?

**Comment by StephMonaco** [comment]
thanks for the change! 
Stephanie
