### ISSUE TITLE
Y scale value for Autoprocessing results display

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#311]
for the graphs coming from the autoprocessing, the X value is correct.
![dlaimephpmmocned](https://user-images.githubusercontent.com/25433590/30803535-3d2c14c6-a1ea-11e7-8ca5-88f576405fb8.png)
but the Y scale should be changed:

completeness : 0->100

I/sigI : 0-> max

Rfac : 0-> max

cc1/2 : 0->100

sigano: 0 -> max

Anom corr -5-> 100

Thanks!

**Comment by antolinos** [comment]
Previously was:
![image](https://user-images.githubusercontent.com/2901169/31601320-cad06852-b259-11e7-9bf1-13a07b8c3a31.png)


With update is:
![image](https://user-images.githubusercontent.com/2901169/31601339-d9de417a-b259-11e7-9e8e-5f76f4b3562f.png)


Rage values given for Anom corr -5-> 100 does not correspond with the actualy range of values (<-20)
Do you still want to give such range?

**Comment by StephMonaco** [comment]
Feedback from Gordon:
The Anom corr should be from [**min value minus 5**] TO 100

**Comment by StephMonaco** [comment]
looks good except for the snapshot representing the graph. e.g: 
truncated snapshot view:
![image](https://user-images.githubusercontent.com/25433590/31769435-def82f0a-b4d3-11e7-8caa-f1647dd83c36.png)
corresponds to enlarged scan (which is correct) 
![image](https://user-images.githubusercontent.com/25433590/31769460-00f8e9aa-b4d4-11e7-9860-137cfa78adb2.png)

**Comment by antolinos** [comment]
It i done now:
![image](https://user-images.githubusercontent.com/2901169/31770989-a26aff84-b4da-11e7-97dc-27d654a517f0.png)

and:
![image](https://user-images.githubusercontent.com/2901169/31771008-b766b98c-b4da-11e7-909d-484342dcf3d1.png)
