### ISSUE TITLE
EXI display of SC for ID30B 

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#326]
The software on ID30B SC interface is now using the general convention  with cells from 1 to 8 with 3 positions each.
Can you please modify the EXI interface as you did for all the other FlexHCDs for ID30B in EXI?
Thanks

**Comment by StephMonaco** [comment]
still old SC view??

**Comment by StephMonaco** [comment]
This issue is back - Can you please fix it today and contact MASSIF-1 if you need to redeploy ISPYB?
Thanks

**Comment by antolinos** [comment]
This should be fine now. Config file was changed

![download 15](https://user-images.githubusercontent.com/2901169/40771083-a794bd00-64bc-11e8-8c59-f88cbbedbbba.png)

**Comment by antolinos** [comment]
It was a problem with the config file
