### ISSUE TITLE
Display Sample changer position in pucks view

### ISSUE THREAD

**Issue by StephMonaco** [ispyb/EXI#339]
In the pucks view for a session, would it be possible to have the position of the puck in the sample changer below the container barcode?
![image](https://user-images.githubusercontent.com/25433590/33651971-e760b892-da67-11e7-8f52-d4d085ed5903.png)
![image](https://user-images.githubusercontent.com/25433590/33652019-160a36fa-da68-11e7-9cd5-8a6b985a6d30.png)
and even better add a title to the page: Beamline / Session date
thanks

**Comment by antolinos** [comment]
![image](https://user-images.githubusercontent.com/2901169/33776607-37ffe9d6-dc42-11e7-8721-922e00fb4446.png)
(To be deployed)
