### ISSUE TITLE
Change space group drop down list to have filter

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/EXI#375]
Stephanie wrote:

Est ce que ce serait possible dans EXI de réduire la liste après avoir tapé le ou les premieres lettres? de meme pour la liste des acronymes de protéines. Une sorte de filtre en fait...

Ca rendrait ce travail plus facile pour les utilisateurs.

**Comment by antolinos** [comment]
Fix is:
https://docs.handsontable.com/0.16.1/demo-dropdown.html
```
 { text :'Forced <br /> Space G.XX', id : 'Space Group', column : {
          width : 55,  
         type: 'autocomplete',
	filter: true,
	source: _.concat([""], ExtISPyB.spaceGroups) }
            }, 
```

Unfortunately it has to be changed in two classes:
containerspreadsheet.js
csvcontainerspreadsheet.js

**Comment by olofsvensson** [comment]
Tested.
