### ISSUE TITLE
Problem debuging EXI locally

### ISSUE THREAD

**Issue by hormiai76** [ispyb/EXI#446]
Hi @antolinos  ,
I'm starting to having a look into the code in order to see if we can pass to EXI at MAXIV and customize some parts as we did in the ISPyB project.
I exduted all the steps in the README.md. 
I run the http-server and configured a javascript debug in my IntelliJ IDEA.
I can login but then I get this error:
```
credentialmanager.js:139 Uncaught ReferenceError: _ is not defined
    at CredentialManager.getCredentialByUserName (credentialmanager.js:139)
    at constructor.handler (mainmenu.js:31)
    at Object.callback (ext-all-debug.js:5198)
    at constructor.fireHandler (ext-all-debug.js:87070)
    at constructor.onClick (ext-all-debug.js:87056)
    at constructor.doFire (ext-all-debug.js:14898)
    at constructor.fire (ext-all-debug.js:14776)
    at constructor.doDispatchEvent (ext-all-debug.js:15467)
    at constructor.dispatch (ext-all-debug.js:13187)
    at constructor.callParent (ext-all-debug.js:7408)
```
I'm still pending update ISPyB to the latest version.
I get the error if I run the server without debugging too.
Do you have any idea about my error?
Alberto Nardella

**Comment by antolinos** [comment]
Try this:
```
bower install lodash --save
grunt --force
```

Let me know if it works. 

For the records lodash is not in bower.json but it is imported as extraneous:
```
lindemaria:/opt2/tomcat/webapps/EXI % /usr/bin/bower list
bower check-new     Checking for new versions of the project dependencies...
exi-ui#5.8.0.0 /opt2/apache-tomcat-7.0.67/webapps/EXI
├── Snap.svg#0.4.1 (latest is 0.5.1)
├─┬ bootstrap#3.3.7 (latest is 4.1.2)
│ └── jquery#2.2.4 (3.3.1 available)
├─┬ bootstrap-multiselect#0.9.15
│ ├── bootstrap#3.3.7 (4.1.2 available)
│ └── jquery#2.2.4 (3.3.1 available)
├── bootstrap-year-calendar#1.1.0
├─┬ dustjs-helpers#1.7.4
│ └── dustjs-linkedin#2.7.5
├── dustjs-linkedin#2.7.5
├── dygraphs#1.1.1 (latest is 2.1.0)
├─┬ eonasdan-bootstrap-datetimepicker#4.17.47
│ ├── jquery#2.2.4 (3.3.1 available)
│ └── moment#2.22.0 (2.22.2 available)
├── file-saver#1.3.8
├── grunt#0.4.5 (latest is 1.0.3)
├─┬ handsontable#0.38.1 (5.0.0 available)
│ ├── moment#2.22.0 (2.22.2 available)
│ ├── numbro#1.11.1 (latest is 2.1.0)
│ └── pikaday#1.6.1
├── html-docx-js#0.3.1
├─┬ jquery-lazy#0.6.4 (latest is 1.7.9)
│ └── jquery#2.2.4 (3.3.1 available)
├── jszip#3.1.5 extraneous
├── jszip-utils#0.0.2 extraneous
├─┬ lightbox2#2.8.2 (latest is 2.10.0)
│ └── jquery#2.2.4 (latest is 3.3.1)
├── lodash#4.17.5 extraneous (4.17.10 available)
├── notifyjs#0.4.2
├── pathjs-amd#0.10.1
├── qunit#1.22.0 (latest is 2.6.1)
├── three#28894ccbc0 extraneous
├── uglymol#0.1.0 extraneous (latest is 0.5.8)
├── vis#4.21.0
└── zeroclipboard#2.3.0 extraneous
```

**Comment by hormiai76** [comment]
now it gives to me another error:
```
Uncaught TypeError: Cannot read property 'isModel' of undefined
    at constructor.extractData (ext-all-debug.js:46182)
    at constructor.callParent (ext-all-debug.js:7408)
    at constructor.extractData (ext-all-debug.js:51174)
    at constructor.readRecords (ext-all-debug.js:46148)
    at constructor.callParent (ext-all-debug.js:7408)
    at constructor.readRecords (ext-all-debug.js:51121)
    at constructor.read (ext-all-debug.js:46080)
    at constructor.read (ext-all-debug.js:46863)
    at constructor.doExecute (ext-all-debug.js:47240)
    at constructor.execute (ext-all-debug.js:47025)
```

This is my bower list:
exi-ui#5.8.0.0 C:\Projects\workspace\EXI
├── Snap.svg#0.4.1 (latest is 0.5.1)
├─┬ bootstrap#3.3.7 (latest is 4.1.2)
│ └── jquery#2.2.4 (3.3.1 available)
├─┬ bootstrap-multiselect#0.9.15
│ ├── bootstrap#3.3.7 (4.1.2 available)
│ └── jquery#2.2.4 (3.3.1 available)
├── bootstrap-year-calendar#1.1.0
├─┬ dustjs-helpers#1.7.4
│ └── dustjs-linkedin#2.7.5
├── dustjs-linkedin#2.7.5
├── dygraphs#1.1.1 (latest is 2.1.0)
├─┬ eonasdan-bootstrap-datetimepicker#4.17.47
│ ├── jquery#2.2.4 (3.3.1 available)
│ └── moment#2.22.2
├── file-saver#1.3.8
├── grunt#0.4.5 (latest is 1.0.3)
├─┬ handsontable#5.0.0
│ ├── moment#2.22.2
│ ├── numbro#2.1.0
│ └── pikaday#1.6.1
├── html-docx-js#0.3.1
├─┬ jquery-lazy#0.6.4 (latest is 1.7.9)
│ └── jquery#2.2.4 (3.3.1 available)
├── jszip#3.1.5 extraneous
├─┬ lightbox2#2.8.2 (latest is 2.10.0)
│ └── jquery#2.2.4 (latest is 3.3.1)
├── lodash#4.17.10
├── notifyjs#0.4.2
├── pathjs-amd#0.10.1
├── qunit#1.22.0 (latest is 2.6.1)
├── three#0949e59f3a extraneous
├── uglymol#0.5.8 extraneous
├── vis#4.21.0
└── zeroclipboard#2.3.0 extraneous

**Comment by antolinos** [comment]
Hi,

Sorry for late reply.

Do the next:
```
grunt dev
```

Then run the application with this URL:
```
http://yourserver:8082/EXI/mx/dev.html
```
and send me the error back with the unminified code. 

I guess your are running EXI with the default configuration file?

**Comment by hormiai76** [comment]
HI,
It works now. There was a problem with the entry I added in the config file.
Thank you
