### ISSUE TITLE
BioSAXS saple plate setup

### ISSUE THREAD

**Issue by maaeli** [ispyb/EXI#454]
There is no "plate" in the view, and it sometimes seems to crash EXI (page needs to be reloaded). I am pretty sure it used to work at some point...

**Comment by pindruse** [comment]
Hi, still not there and I confirm if clinking (in View) from Online Data Analysis to Sample Plate View back it returns empty page (if it works once try second time ;-) and only way to recover some useful info is to go 'Home'...

**Comment by maaeli** [comment]
Since this is fixed (thanks a lot) we observe #469. Might be related?
