### ISSUE TITLE
Improvements of MR result display

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/EXI#472]
Max and I had a preliminary discussion on how to improve the display of MR results in EXI:
- The MR results should be displayed like the SAD results:
![image](https://user-images.githubusercontent.com/1306808/48199386-2dd17c00-e35c-11e8-87a6-8f17a6ee19ba.png)
- The MR map file should be displayed like for the SAD results

**Comment by ispyb** [comment]
Deployed.
