### ISSUE TITLE
Missing EDNA Characterisation Results

### ISSUE THREAD

**Issue by hormiai76** [ispyb/EXI#491]
Hi,
I would like to know if the "Characterisation Results" tab of the ISPyB UI has been removed in EXI or not.
I can see the results in the session page but I cannot see any link to see the dnafiles (edna_log.html, indexing_log.html, best_log.html, ...)
Alberto

**Comment by olofsvensson** [comment]
Hi Alberto,

Indeed the way characterisation results are displayed has changed. In the (old) ISPyB GUI the results were stored as web pages (in the dnafiles directory). As EXI cannot display HTML files the same way as the ISPyB UI we now store the characterisation results in a JSON file.

Also, the ISPyB GUI 'discovers' the characterisation results by looking for files in the 'dnafiles' directory. In EXI the characterisation results is stored in the Workflows table, even though we don't use the workflow engine (yet) for characterisations. There's no problem for you too also use the Workflow table even if you don't have a workflow engine.

If you use the latest EDNA characterisation plugin 'EDPluginControlInterfaceToMXCuBEv1_4' you can get both the (old) HTML files and the (new) json file uploaded to ISPyB, see:
https://github.com/olofsvensson/edna-mx/blob/29e70a23477fdd6bb696e7486493a633f5c390aa/mxv1/plugins/EDPluginControlInterfaceToMXCuBE-v1.4/plugins/EDPluginControlInterfaceToMXCuBEv1_4.py#L384-L423

Regards,

Olof

**Comment by hormiai76** [comment]
Thank you Olof, we fixed the EDNA plugin and now I got the workflow in EXI.
Regards,
Alberto
