### ISSUE TITLE
Lab contact's WebService needs to store and get the Lab name and the Lab address

### ISSUE THREAD

**Issue by sergiogf93** [ispyb/EXI#68]
Right now we can edit the Lab name and the Lab address for a given Lab contact but it's not persisted:

![image](https://cloud.githubusercontent.com/assets/22632506/22639895/96ce1506-ec50-11e6-82af-30b5ef43148d.png)

We need to save this values so that they can be shown, just like at the current version of ispyb:

![image](https://cloud.githubusercontent.com/assets/22632506/22639928/b773891c-ec50-11e6-94c2-95e99e541c27.png)

**Comment by antolinos** [comment]
Out of curiosity: why has it been closed?

**Comment by sergiogf93** [comment]
This was one of the features added with the pull request #77 .
