### ISSUE TITLE
Improvements of "Data Collections" tab

### ISSUE THREAD

**Issue by olofsvensson** [ispyb/EXI#69]
The current design of this tab:
![image](https://cloud.githubusercontent.com/assets/1306808/22640458/06a4e83a-ec53-11e6-9060-1f51190096e1.png)

New suggested design:
![image](https://cloud.githubusercontent.com/assets/1306808/22640500/35a33092-ec53-11e6-8e7b-93c6529f8651.png)

**Comment by antolinos** [comment]
Added to alpha version
