### ISSUE TITLE
Allow beamline reset when unloading the sample changer in Prepare Experiment

### ISSUE THREAD

**Issue by sergiogf93** [ispyb/EXI#87]
When the button "Unload all" is clicked, the beamline should be set to null for each container:

![image](https://cloud.githubusercontent.com/assets/22632506/22781285/1eab2f72-eec2-11e6-808e-84444b4b2801.png)

It would be necessary that the method:

**EXI.getDataAdapter().proposal.dewar.updateSampleLocation([containerId], [beamline], [sampleChangerLocation]);**

Could receive an empty string or a null value at the beamline parameter to achieve this.

**Comment by antolinos** [comment]
This issue corresponds to ISPyB and have been solved here:
https://github.com/antolinos/ISPyB/commit/a956668ccee59c72cf2510d464a5e4db277fd6d2
