### ISSUE TITLE
Shipping fields needs to be updated when a shipment is sent to ESRF

### ISSUE THREAD

**Issue by sergiogf93** [ispyb/EXI#94]
The method **EXI.getDataAdapter().proposal.shipping.saveShipment**
with the URL: **/{token}/proposal/{proposal}/shipping/save'**

Needs to update **shippingStatus**, **deliveryAgentDeliveryDate**, **deliveryAgentShippingDate**, and for each dewar in dewarVOs **trackingNumberToSynchrotron**.

**Comment by antolinos** [comment]
Could we close this issue?

**Comment by sergiogf93** [comment]
Well, we need a method that will be executed when a shipment is sent to ESRF. This method should update the **shippingStatus, deliveryAgentDeliveryDate, deliveryAgentShippingDate** of a given shipment and should also update the **trackingNumberToSynchrotron** for each dewar in the dewarVOs of the shipment.

Maybe we need to create a different method instead of changing the already existing **saveShipment** method.
