### ISSUE TITLE
Needed values for the sessions at the welcome page

### ISSUE THREAD

**Issue by sergiogf93** [ispyb/EXI#97]
The session grid interface is being changed into something like this:

![image](https://cloud.githubusercontent.com/assets/22632506/22923345/6a3d0388-f2a1-11e6-961c-3e5da92402ff.png)

We need to display the workflowCount, the autoprocResultsCount and the phasingResultsCount for each sessions.

It would be nice if these parameters were returned by the following urls:

**this.get('/{token}/proposal/{0}/session/list'.format([proposal]));**
**this.get('/{token}/proposal/session/beamlineoperator/{0}/list'.format([beamlineOperator]));
this.get('/{token}/proposal/{0}/session/date/{1}/{2}/list'.format([proposal, startDate, endDate]));
this.get('/{token}/proposal/session/date/{0}/{1}/list'.format([startDate, endDate]));**

**Comment by antolinos** [comment]
After discussion (Steph et al.) autoproc and workflow is more for manager but phasing is really useful for users.
So, it would be good to get at least a tick that indicates that phasing has run on a session

**Comment by sergiogf93** [comment]
Ok. So then we would need some kind of flag to show that a session has phasing results. I created an issue for this antolinos/ispyb-js-api#17

**Comment by antolinos** [comment]
Is it closed because is done or not needed any more?
